const settings = {
  'weather': {
    'apiKey': '5c084e3b39a49a5974701c58069592c6',
    'apiRequestDelay': 100,
    'location': 'Toronto,CA',
    'units': 'metric',
    'forecastPeriod': 27,
    'pollingInterval': 5,
    'precipitationMax': 10,
    'width': 1280,
    'height': 80,
    'margins': {
      'top': 0,
      'right': 0,
      'bottom': 0,
      'left': 0
    }
  },
  'ttcRoutes': {
    'maxDepartures': 2,
    'pollingInterval': 1,
    'routes': [ {
      'id': 26,
      'stopEastbound': 7919,
      'stopWestbound': 3652,
      'warningThreshold': 15,
      'dangerThreshold': 10,
      'missedThreshold': 5
    }, {
      'id': 30,
      'stopEastbound': 4444,
      'stopWestbound': 4744,
      'warningThreshold': 10,
      'dangerThreshold': 5,
      'missedThreshold': 2
    }, {
      'id': 40,
      'stopEastbound': 4444,
      'stopWestbound': 4744,
      'warningThreshold': 10,
      'dangerThreshold': 5,
      'missedThreshold': 2
    } ]
  },
  'iconMap': {
    '200': { icon: 'thunderstorm', description: 'Sample description' },
    '201': { icon: 'thunderstorm', description: 'Sample description' },
    '202': { icon: 'thunderstorm', description: 'Sample description' },
    '210': { icon: 'lightning', description: 'Sample description' },
    '211': { icon: 'lightning', description: 'Sample description' },
    '212': { icon: 'lightning', description: 'Sample description' },
    '221': { icon: 'lightning', description: 'Sample description' },
    '230': { icon: 'thunderstorm', description: 'Sample description' },
    '231': { icon: 'thunderstorm', description: 'Sample description' },
    '232': { icon: 'thunderstorm', description: 'Sample description' },
    '300': { icon: 'sprinkle', description: 'Sample description' },
    '301': { icon: 'sprinkle', description: 'Sample description' },
    '302': { icon: 'rain', description: 'Sample description' },
    '310': { icon: 'rain-mix', description: 'Sample description' },
    '311': { icon: 'rain', description: 'Sample description' },
    '312': { icon: 'rain', description: 'Sample description' },
    '313': { icon: 'showers', description: 'Sample description' },
    '314': { icon: 'rain', description: 'Sample description' },
    '321': { icon: 'sprinkle', description: 'Sample description' },
    '500': { icon: 'sprinkle', description: 'Sample description' },
    '501': { icon: 'rain', description: 'Sample description' },
    '502': { icon: 'rain', description: 'Sample description' },
    '503': { icon: 'rain', description: 'Sample description' },
    '504': { icon: 'rain', description: 'Sample description' },
    '511': { icon: 'rain-mix', description: 'Sample description' },
    '520': { icon: 'showers', description: 'Sample description' },
    '521': { icon: 'showers', description: 'Sample description' },
    '522': { icon: 'showers', description: 'Sample description' },
    '531': { icon: 'storm-showers', description: 'Sample description' },
    '600': { icon: 'snow', description: 'Sample description' },
    '601': { icon: 'snow', description: 'Sample description' },
    '602': { icon: 'sleet', description: 'Sample description' },
    '611': { icon: 'rain-mix', description: 'Sample description' },
    '612': { icon: 'rain-mix', description: 'Sample description' },
    '615': { icon: 'rain-mix', description: 'Sample description' },
    '616': { icon: 'rain-mix', description: 'Sample description' },
    '620': { icon: 'rain-mix', description: 'Sample description' },
    '621': { icon: 'snow', description: 'Sample description' },
    '622': { icon: 'snow', description: 'Sample description' },
    '701': { icon: 'showers', description: 'Sample description' },
    '711': { icon: 'smoke', description: 'Sample description' },
    '721': { icon: 'day-haze', description: 'Sample description' },
    '731': { icon: 'dust', description: 'Sample description' },
    '741': { icon: 'fog', description: 'Sample description' },
    '761': { icon: 'dust', description: 'Sample description' },
    '762': { icon: 'dust', description: 'Sample description' },
    '771': { icon: 'cloudy-gusts', description: 'Sample description' },
    '781': { icon: 'tornado', description: 'Sample description' },
    '800': { icon: 'day-sunny', description: 'Sample description' },
    '801': { icon: 'cloudy-gusts', description: 'Sample description' },
    '802': { icon: 'cloudy-gusts', description: 'Sample description' },
    '803': { icon: 'cloudy-gusts', description: 'Sample description' },
    '804': { icon: 'cloudy', description: 'Sample description' },
    '900': { icon: 'tornado', description: 'Sample description' },
    '901': { icon: 'storm-showers', description: 'Sample description' },
    '902': { icon: 'hurricane', description: 'Sample description' },
    '903': { icon: 'snowflake-cold', description: 'Sample description' },
    '904': { icon: 'hot', description: 'Sample description' },
    '905': { icon: 'windy', description: 'Sample description' },
    '906': { icon: 'hail', description: 'Sample description' },
    '957': { icon: 'strong-wind', description: 'Sample description' },
    '200-day': { icon: 'day-thunderstorm', description: 'Sample description' },
    '201-day': { icon: 'day-thunderstorm', description: 'Sample description' },
    '202-day': { icon: 'day-thunderstorm', description: 'Sample description' },
    '210-day': { icon: 'day-lightning', description: 'Sample description' },
    '211-day': { icon: 'day-lightning', description: 'Sample description' },
    '212-day': { icon: 'day-lightning', description: 'Sample description' },
    '221-day': { icon: 'day-lightning', description: 'Sample description' },
    '230-day': { icon: 'day-thunderstorm', description: 'Sample description' },
    '231-day': { icon: 'day-thunderstorm', description: 'Sample description' },
    '232-day': { icon: 'day-thunderstorm', description: 'Sample description' },
    '300-day': { icon: 'day-sprinkle', description: 'Sample description' },
    '301-day': { icon: 'day-sprinkle', description: 'Sample description' },
    '302-day': { icon: 'day-rain', description: 'Sample description' },
    '310-day': { icon: 'day-rain', description: 'Sample description' },
    '311-day': { icon: 'day-rain', description: 'Sample description' },
    '312-day': { icon: 'day-rain', description: 'Sample description' },
    '313-day': { icon: 'day-rain', description: 'Sample description' },
    '314-day': { icon: 'day-rain', description: 'Sample description' },
    '321-day': { icon: 'day-sprinkle', description: 'Sample description' },
    '500-day': { icon: 'day-sprinkle', description: 'Sample description' },
    '501-day': { icon: 'day-rain', description: 'Sample description' },
    '502-day': { icon: 'day-rain', description: 'Sample description' },
    '503-day': { icon: 'day-rain', description: 'Sample description' },
    '504-day': { icon: 'day-rain', description: 'Sample description' },
    '511-day': { icon: 'day-rain-mix', description: 'Sample description' },
    '520-day': { icon: 'day-showers', description: 'Sample description' },
    '521-day': { icon: 'day-showers', description: 'Sample description' },
    '522-day': { icon: 'day-showers', description: 'Sample description' },
    '531-day': { icon: 'day-storm-showers', description: 'Sample description' },
    '600-day': { icon: 'day-snow', description: 'Sample description' },
    '601-day': { icon: 'day-sleet', description: 'Sample description' },
    '602-day': { icon: 'day-snow', description: 'Sample description' },
    '611-day': { icon: 'day-rain-mix', description: 'Sample description' },
    '612-day': { icon: 'day-rain-mix', description: 'Sample description' },
    '615-day': { icon: 'day-rain-mix', description: 'Sample description' },
    '616-day': { icon: 'day-rain-mix', description: 'Sample description' },
    '620-day': { icon: 'day-rain-mix', description: 'Sample description' },
    '621-day': { icon: 'day-snow', description: 'Sample description' },
    '622-day': { icon: 'day-snow', description: 'Sample description' },
    '701-day': { icon: 'day-showers', description: 'Sample description' },
    '711-day': { icon: 'smoke', description: 'Sample description' },
    '721-day': { icon: 'day-haze', description: 'Sample description' },
    '731-day': { icon: 'dust', description: 'Sample description' },
    '741-day': { icon: 'day-fog', description: 'Sample description' },
    '761-day': { icon: 'dust', description: 'Sample description' },
    '762-day': { icon: 'dust', description: 'Sample description' },
    '781-day': { icon: 'tornado', description: 'Sample description' },
    '800-day': { icon: 'day-sunny', description: 'Sample description' },
    '801-day': { icon: 'day-cloudy-gusts', description: 'Sample description' },
    '802-day': { icon: 'day-cloudy-gusts', description: 'Sample description' },
    '803-day': { icon: 'day-cloudy-gusts', description: 'Sample description' },
    '804-day': { icon: 'day-sunny-overcast', description: 'Sample description' },
    '900-day': { icon: 'tornado', description: 'Sample description' },
    '902-day': { icon: 'hurricane', description: 'Sample description' },
    '903-day': { icon: 'snowflake-cold', description: 'Sample description' },
    '904-day': { icon: 'hot', description: 'Sample description' },
    '906-day': { icon: 'day-hail', description: 'Sample description' },
    '957-day': { icon: 'strong-wind', description: 'Sample description' },
    '200-night': { icon: 'night-alt-thunderstorm', description: 'Sample description' },
    '201-night': { icon: 'night-alt-thunderstorm', description: 'Sample description' },
    '202-night': { icon: 'night-alt-thunderstorm', description: 'Sample description' },
    '210-night': { icon: 'night-alt-lightning', description: 'Sample description' },
    '211-night': { icon: 'night-alt-lightning', description: 'Sample description' },
    '212-night': { icon: 'night-alt-lightning', description: 'Sample description' },
    '221-night': { icon: 'night-alt-lightning', description: 'Sample description' },
    '230-night': { icon: 'night-alt-thunderstorm', description: 'Sample description' },
    '231-night': { icon: 'night-alt-thunderstorm', description: 'Sample description' },
    '232-night': { icon: 'night-alt-thunderstorm', description: 'Sample description' },
    '300-night': { icon: 'night-alt-sprinkle', description: 'Sample description' },
    '301-night': { icon: 'night-alt-sprinkle', description: 'Sample description' },
    '302-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '310-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '311-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '312-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '313-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '314-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '321-night': { icon: 'night-alt-sprinkle', description: 'Sample description' },
    '500-night': { icon: 'night-alt-sprinkle', description: 'Sample description' },
    '501-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '502-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '503-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '504-night': { icon: 'night-alt-rain', description: 'Sample description' },
    '511-night': { icon: 'night-alt-rain-mix', description: 'Sample description' },
    '520-night': { icon: 'night-alt-showers', description: 'Sample description' },
    '521-night': { icon: 'night-alt-showers', description: 'Sample description' },
    '522-night': { icon: 'night-alt-showers', description: 'Sample description' },
    '531-night': { icon: 'night-alt-storm-showers', description: 'Sample description' },
    '600-night': { icon: 'night-alt-snow', description: 'Sample description' },
    '601-night': { icon: 'night-alt-sleet', description: 'Sample description' },
    '602-night': { icon: 'night-alt-snow', description: 'Sleet' },
    '611-night': { icon: 'night-alt-rain-mix', description: 'Sample description' },
    '612-night': { icon: 'night-alt-rain-mix', description: 'Sample description' },
    '615-night': { icon: 'night-alt-rain-mix', description: 'Sample description' },
    '616-night': { icon: 'night-alt-rain-mix', description: 'Sample description' },
    '620-night': { icon: 'night-alt-rain-mix', description: 'Sample description' },
    '621-night': { icon: 'night-alt-snow', description: 'Sample description' },
    '622-night': { icon: 'night-alt-snow', description: 'Sample description' },
    '701-night': { icon: 'night-alt-showers', description: 'Sample description' },
    '711-night': { icon: 'smoke', description: 'Sample description' },
    '721-night': { icon: 'day-haze', description: 'Sample description' },
    '731-night': { icon: 'dust', description: 'Sample description' },
    '741-night': { icon: 'night-fog', description: 'Sample description' },
    '761-night': { icon: 'dust', description: 'Sample description' },
    '762-night': { icon: 'dust', description: 'Sample description' },
    '781-night': { icon: 'tornado', description: 'Sample description' },
    '800-night': { icon: 'night-clear', description: 'Sample description' },
    '801-night': { icon: 'night-alt-cloudy-gusts', description: 'Sample description' },
    '802-night': { icon: 'night-alt-cloudy-gusts', description: 'Sample description' },
    '803-night': { icon: 'night-alt-cloudy-gusts', description: 'Sample description' },
    '804-night': { icon: 'night-alt-cloudy', description: 'Sample description' },
    '900-night': { icon: 'tornado', description: 'Sample description' },
    '902-night': { icon: 'hurricane', description: 'Sample description' },
    '903-night': { icon: 'snowflake-cold', description: 'Sample description' },
    '904-night': { icon: 'hot', description: 'Sample description' },
    '906-night': { icon: 'night-alt-hail', description: 'Sample description' },
    '957-night': { icon: 'strong-wind', description: 'Sample description' }
  }
};

export default Object.freeze( settings );
